names:
  - android
  - api
  - app
  - apps
  - bean
  - beans
  - brother
  - brothers
  - campaign
  - circus
  - circuses
  - comment
  - comments
  - contributor
  - contributors
  - contest
  - contents
  - detail
  - details
  - edit
  - entry
  - entries
  - faq
  - guide
  - help
  - history
  - home
  - image
  - images
  - img
  - index
  - info
  - inq
  - iphone
  - javascript
  - javascripts
  - kaminari
  - layout
  - layouts
  - library
  - login
  - logout
  - manage
  - manual
  - message
  - messages
  - new
  - news
  - order
  - original
  - payment
  - plugin
  - plugins
  - print
  - register
  - release
  - reset_password
  - resign
  - resque
  - root
  - score_mailer
  - service
  - session
  - sessions
  - setting
  - settings
  - shared
  - shop
  - static_page
  - static_pages
  - signup
  - sitemap
  - store
  - support
  - tool
  - tour
  - user
  - users
  - vote
  - votes
